package paint;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

public class VistaPrevia extends javax.swing.JPanel {

    private float trazo;
    private Color fondo;
    private Boolean puntear;
    private float dash[] = {5.0f,5.0f};

    public VistaPrevia() {
        initComponents();
        trazo=1.0f;
        fondo = Color.white;
        puntear = false;
    }

    @Override
    public void paint(java.awt.Graphics g){
        super.paint(g);
        Graphics2D g2d = (Graphics2D)g;
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);
        if(puntear)
            g2d.setStroke(new BasicStroke(trazo,BasicStroke.CAP_BUTT,BasicStroke.CAP_BUTT,10.0f,dash,0.0f));
        else
             g2d.setStroke(new BasicStroke(trazo,BasicStroke.CAP_BUTT,BasicStroke.CAP_BUTT));
        g2d.setPaint(fondo);
        g2d.fillRect(0,0, this.getWidth(),this.getHeight());
        g2d.setPaint(this.getForeground());
        g2d.drawLine(10,10,this.getWidth()-10,this.getHeight()-10);
    }

    public void set(float t){
       trazo = t;
       repaint();
    }

    public void setFondo(Color c){
        fondo = c;
        repaint();
    }

    public Color getFondo(){
        return fondo;
    }

    public void setPunteo(Boolean b){
        puntear = b;
        repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
